site_name: "MRIQC :: SOPs"
site_description: Standard operating procedures (SOPs) associated to our "Quality Control in functional MRI studies with MRIQC and fMRIPrep" paper. 
site_author: The AxonLab
site_url: https://github.com/TheAxonLab/frontiers-sops-QC.git
google_analytics: ['UA-170131052-1', 'www.nipreps.org']

# Copyright
copyright: Copyright &copy; 2022

nav:
    - Home: index.md
    - Change History: changes.md
    - Quality Assessment and Control: qa-qc.md
    - Exclusion Criteria: exclusion_criteria.md
    - Release of data: release.md
theme:
  name: material
  features:
    - tabs

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - markdown_include.include:
      base_path: docs

extra_css:
  - stylesheets/extra.css
